spring.application.name=api-gateway

server.port=8123

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
jwt.secret={cipher}6d2bef7904191e69e8d16b635ac97bd7e0842104f30d63f707a498507af60e4f51791093fe317d0c30e56379e79fc188f164204b0f6eeab578b7c0cb98d8c97e
