spring.application.name=order-service
server.port=8099


#MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/orders
spring.datasource.username=root
spring.datasource.password={cipher}5949f2d5e0ab20c375e518e9948d280788c62716ee00d94686adfe1a9a4118249bc964d05e2e881a1fdcfd8f6470e167
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#Kafka Consumer
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
# retry and backoff
spring.kafka.listener.max-attempts=3
spring.kafka.listener.backoff.initial-interval=1000
spring.kafka.listener.backoff.max-interval=5000
spring.kafka.listener.backoff.multiplier=2.0

# Product retry and circuitbreaker
resilience4j.retry.instances.productServiceRetry.maxAttempts=3
resilience4j.retry.instances.productServiceRetry.wait-duration=2s
resilience4j.retry.instances.productServiceRetry.enable-exponential-backoff=true
resilience4j.retry.instances.productServiceRetry.exponential-backoff-multiplier=2.0

resilience4j.circuitbreaker.instances.productServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productServiceCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productServiceCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.productServiceCB.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.productServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.retry.instances.inventoryServiceRetry.retry-exceptions=java.lang.Exception
resilience4j.retry.instances.inventoryServiceRetry.ignore-exceptions=com.tech.order_service.exceptions.ProductUnavailableException

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

#Inventory retry and circuitbreaker
resilience4j.retry.instances.inventoryServiceRetry.maxAttempts=3
resilience4j.retry.instances.inventoryServiceRetry.wait-duration=2s
resilience4j.retry.instances.inventoryServiceRetry.enable-exponential-backoff=true
resilience4j.retry.instances.inventoryServiceRetry.exponential-backoff-multiplier=2.0

resilience4j.circuitbreaker.instances.inventoryServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryServiceCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventoryServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventoryServiceCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventoryServiceCB.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.retry.instances.inventoryServiceRetry.retry-exceptions=java.lang.Exception
resilience4j.retry.instances.inventoryServiceRetry.ignore-exceptions=com.tech.order_service.exceptions.OutOfStockException

#LOGS Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] [order-service] %-5level %logger{36} - %msg%n


#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Connection and read timeout
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=10000
